### ISSUE TITLE
Joins

### ISSUE THREAD

**Issue by jsommr** [DanielLavrushin/LinqToSolr#1]
Hi

So glad you created this library. The other two are way too heavy, and this is exactly the way it should be done.

Are there any plans to support query time joins? Something that also supports joining across cores, like in this example: https://stackoverflow.com/questions/12665797/is-solr-4-0-capable-of-using-join-for-multiple-core

**Comment by DanielLavrushin** [comment]
Hu nerfpops,
Thanks for your feedback!
I have updated the librar to [version 2.1.0.5](https://www.nuget.org/packages/LinqToSolr/https://www.nuget.org/packages/LinqToSolr/). It includes join feature.
Hovewer, be aware that joins in SOLR are not similar to joins in SQL.


> , it's important to note that Joins in Solr are not really equivalent to SQL Joins because no information about the table being joined "from" is carried forward into the final result. A more appropriate SQL analogy would be an "inner query"

 you can find[ wiki page how ](https://github.com/DanielLavrushin/LinqToSolr/wiki/Perform-Join)to perform simple join request with this library. 
Hope it will help.

**Comment by jsommr** [comment]
Nice! Thank you.
