### ISSUE TITLE
SoftCommit

### ISSUE THREAD

**Issue by davalillo** [DanielLavrushin/LinqToSolr#2]
How do you see to implement "soft commit" in AddOrUpdate and Delete methods?

**Comment by DanielLavrushin** [comment]
Hi Davalillo,

as I understood soft commit is just an extra parameter (softcommit=true) which need to be passed to update/delete handler?

**Comment by davalillo** [comment]
I think so. I can try to implement this by myself and upload it to the repository.

**Comment by DanielLavrushin** [comment]
Hi devalillo,

I made this change already yesterday :)
try to update the lib to a most recent [version (2.1.0.5)](https://www.nuget.org/packages/LinqToSolr/)
You will find an overload method for Delete and AddOrUpdate methods accepting a bool softCommit parameter - set it to true.
