### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by jsommr** [DanielLavrushin/LinqToSolr#3]
Just curious, because I see that your webclient has async code: Are there any plans to implement something like Entity Framework's ToListAsync?

**Comment by DanielLavrushin** [comment]
I am not very familiar with async programming, do you mean something similar to this? Or you need a full implementation of calling async methods of webclient?

```
public static System.Threading.Tasks.Task<List<TSource>> ToListAsync<TSource>(this IQueryable<TSource> source)
        {
           return System.Threading.Tasks.Task.Run(() => source.ToList());
        }
```

**Comment by jsommr** [comment]
I thought about that as well, but when looking at the code in Entity Framework, it seems they have an IDbAsyncEnumerable that handles things. The "correct" way would probably be a ToListAsync that calls the webclient's async methods, but I'm no expert in LinqProviders/IQueryable. Don't know if Task.Run is just as good performance wise. Oh well, hopefully I get the time to look into it. Do you want me to close the issue or should it remain open?

**Comment by DanielLavrushin** [comment]
thanks for your comment. I think this is a good request. Leave it opened for a while. I will also try to look how they implemented it in EF.

**Comment by DanielLavrushin** [comment]
ToListAsync is available in version3
```csharp
    public async Task SelectWithWhereToStringListTest()
    {
        var docs = await Service.AsQueryable<SolrDocument>().Take(50).Where(x => x.Name.StartsWith("A")).ToListAsync();
     }
```
