### ISSUE TITLE
adding /solr/ in request path

### ISSUE THREAD

**Issue by pittsrn** [DanielLavrushin/LinqToSolr#4]
I'm testing LinqToSolr and it looks promising for our purposes. However, there is one small issue (so far) that I had to change the code for. In LinqToSolrService.PrepareQueryRequest, you have /solr/ hard-coded in the path. This causes a 404 for us because our paths look like this http://this.that.com/poolname/collectionname/select. Can you make that hard-coded value some sort of optional value?
Thanks!

**Comment by DanielLavrushin** [comment]
Hi,
I just added a new version 2.1.0.9, you could setup your custom path in the Configuration.  For example:
`solrService.Configuration.SolrPath = "poolname";`

[changeset](https://github.com/DanielLavrushin/LinqToSolr/commit/4b02577d5f84e7ffbcfb07c9367a3f82fecade12)

[nuget](https://www.nuget.org/packages/LinqToSolr/2.1.0.9)
