### ISSUE TITLE
Add support for BasicAuthentication

### ISSUE THREAD

**Issue by setiawana** [DanielLavrushin/LinqToSolr#7]
Any reason why you disable the HttpBasicAuthenticator in the LinqToSolrService.cs as below:
`if (!string.IsNullOrEmpty(Configuration.SolrLogin) && !string.IsNullOrEmpty(Configuration.SolrPassword))
            {
                //   Client.Authenticator = new HttpBasicAuthenticator(Configuration.SolrLogin, Configuration.SolrPassword);
            }`

**Comment by DanielLavrushin** [comment]
it is supported in version3
```csharp
     var endpoint = new LinkToSolrEndpoint(solrUrl, solrUser, solrPassword);
     var config = new LinqToSolrConfiguration(endpoint).MapCoreFor<SolrDocument>(solrCore);
     var service = new LinqToSolrService(config);
```
